name: updater-ver-num
description: CI to update project version number in pyproject.toml, only works with uv projects.

inputs:
  github_token:
    description: 'GitHub Token'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Get the latest commit message
      id: get-commit-msg
      run: |
        COMMIT_MSG=$(git log -1 --pretty=format:%s)
        echo "commit_msg=$COMMIT_MSG" >> $GITHUB_OUTPUT
      shell: bash
    
    - name: Version bump detected
      if: ${{ contains(steps.get-commit-msg.outputs.commit_msg, 'Bump version') }}
      run: echo "Version bump detected."
      shell: bash

    - name: Install uv
      if: ${{ !contains(steps.get-commit-msg.outputs.commit_msg, 'Bump version') }}
      uses: astral-sh/setup-uv@v5

    - name: Bump version and update lock file
      if: ${{ !contains(steps.get-commit-msg.outputs.commit_msg, 'Bump version') }}
      run: uv version --bump patch && uv lock
      shell: bash

    - name: Commit changes
      if: ${{ !contains(steps.get-commit-msg.outputs.commit_msg, 'Bump version') }}
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add pyproject.toml uv.lock
        git diff --quiet && git diff --staged --quiet || (git commit -m "chore(ver): Bump version")
      shell: bash

    - name: Push changes
      if: ${{ !contains(steps.get-commit-msg.outputs.commit_msg, 'Bump version') }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}
